version: '3.8'

services:
  app:
    image: yuritabacof/api_nuvem:latest  # Usando a imagem do Docker Hub
    container_name: app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL:-projeto}
      - SECRET_KEY=${SECRET_KEY:-projeto}
    depends_on:
      - database
    #env_file:
    #  - .env  # Carrega as variáveis de ambiente do arquivo .env

  database:
    image: postgres:13
    container_name: database
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-projeto}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-projeto}
      - POSTGRES_DB=${POSTGRES_DB:-projeto}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    #env_file:
    #  - .env  # Carrega as variáveis de ambiente do arquivo .env

volumes:
  postgres_data: