# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: api-nuvem-service
spec:
  type: LoadBalancer
  selector:
    app: api-nuvem
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000