name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3  # Use the latest version

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs-material mkdocs-mermaid2-plugin

      - name: Build MkDocs site
        run: |
          mkdocs build --verbose --clean

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site