name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # O deploy será acionado toda vez que você fizer um push na branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checar o código
        uses: actions/checkout@v2

      - name: Instalar o Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Instalar dependências MkDocs
        run: |
          pip install mkdocs mkdocs-material mkdocs-mermaid2-plugin

      - name: Publicar no GitHub Pages
        run: |
          mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token para autenticação